sudo: required
dist: xenial

language: python

python:
  - "3.7"

# blocklist
branches:
  except:
  - master

# safelist
branches:
  only:
  - af/acq_param_ci

before_install:
  - sudo rm -rf ~/.nvm
  - curl -sL https://deb.nodesource.com/setup_current.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm install -g bids-validator

install:
  - git clone https://github.com/spine-generic/spine-generic.git code/spine-generic
  - cd code/spine-generic
  - git checkout af/acq_param_ci
  - pip install -e .
  - source ~/virtualenv/python3.7/bin/activate
  - cd ../..

script: 
  - sg_params_checker -path-in ./
  - bids-validator ./
  