language: python

python:
  - "3.7"

# blocklist
branches:
  except:
  - master

# safelist
branches:
  only:
  - af/acq_param_ci
  
install:
  - git clone https://github.com/spine-generic/spine-generic.git
  - git checkout af/acq_param_ci
  - cd spine-generic/
  - source /home/travis/.bashrc
  - pip install -e .
  - source /home/travis/virtualenv/python3.7.1/bin/activate
  - cd ..

script: 
  - sg_params_checker -path-in ./
